language: node_js
node_js:
  - 10

env:
  - NODE_ENV=development

before_install:
  - npm i -g codecov

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run gen
  - npm test
  - codecov

notifications:
  email: false